apiVersion: v1
kind: Service
metadata:
  name: argodemo-dev
  namespace: argodemo
  labels:
    app: argodemo-dev
spec:
  selector:
    app: argodemo-dev
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP