apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argodemo-dev1
  # Deploy the ArgoCD Application resource into the openshift-operators namespace
  namespace: openshift-operators
spec:
  project: default

  source:
    # Point this at your fork / clone of the repo
    repoURL: https://github.com/esath/argodemo.git
    targetRevision: dev1
    # ArgoCD watches the k8s-dev1/ directory for manifest changes
    path: k8s-dev1

  destination:
    server: https://kubernetes.default.svc
    namespace: argodemo-dev1

  syncPolicy:
    # Automatically sync when ArgoCD detects a diff
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true